[tool.poetry]
name = "edlm-search"
version = "0.1.0"
description = "LLM-based architecture search for time-series forecasting on ETT datasets"
readme = "README.md"
authors = ["Неронов Роман, Фазлыев Альберт"]
packages = [{ include = "edlm_search", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
beautifulsoup4 = ">=4.14.2"
dotenv = ">=0.9.9"
jinja2 = ">=3.1.6"
lxml = ">=6.0.2"
numpy = ">=2.3.4"
openai = { version = ">=2.5.0", extras = ["aiohttp"] }
pandas = ">=2.3.3"
pyarrow = ">=22.0.0"
scikit-learn = ">=1.7.2"
torch = ">=2.9.0"
zeus = ">=0.12.3"
tblib = ">=3.0.0"
optuna = ">=4.0.0"
matplotlib = "^3.10.7"
notebook = "^7.4.7"
tiktoken = "^0.12.0"

[tool.poetry.group.dev.dependencies]
basedpyright = ">=1.31.7"
ruff = ">=0.14.0"

[tool.ruff]
line-length = 96

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "UP",
    "B",
    "I",
    "D",
    "SIM",
]
ignore = [
    "E501",
    "E402",
    "E731",
    "EM102",
    "W191",
    "E111",
    "E114",
    "E117",
    "D100",
    "D202",
    "D203",
    "D204",
    "D206",
    "D212",
    "D300",
    "D400",
    "D401",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC002",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.basedpyright]
reportIgnoreCommentWithoutRule = false
reportUnnecessaryTypeIgnoreComment = false
reportAny = false
reportExplicitAny = false
reportMissingTypeStubs = false
reportUnusedCallResult = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownLambdaType = false
reportUnknownArgumentType = false
reportUnknownParameterType = false
reportMissingParameterType = false
reportUnannotatedClassAttribute = false

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"